/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 02:50:06 GMT 2026
 */

package org.confucius.commons.lang.io.scanner;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Set;
import org.confucius.commons.lang.io.scanner.SimpleClassScanner;

public class SimpleClassScannerTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleClassScanner simpleClassScanner0 = new SimpleClassScanner();
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      Set<Class<?>> set0 = simpleClassScanner0.scan(classLoader0, "io", false, false);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleClassScanner simpleClassScanner0 = new SimpleClassScanner();
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      Set<Class<?>> set0 = simpleClassScanner0.scan(classLoader0, "10.1");
  }
}
