/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:20:03 GMT 2026
 */

package org.confucius.commons.lang.io.scanner;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.URL;
import java.util.Set;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import org.confucius.commons.lang.io.scanner.SimpleJarEntryScanner;
import org.evosuite.runtime.mock.java.net.MockURL;

public class SimpleJarEntryScannerTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleJarEntryScanner simpleJarEntryScanner0 = new SimpleJarEntryScanner();
      Set<JarEntry> set0 = simpleJarEntryScanner0.scan((JarFile) null, true);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleJarEntryScanner simpleJarEntryScanner0 = SimpleJarEntryScanner.INSTANCE;
      URL uRL0 = MockURL.getFileExample();
      Set<JarEntry> set0 = simpleJarEntryScanner0.scan(uRL0, false);
  }
}
