/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 03:19:35 GMT 2026
 */

package ru.stqa.selenium.decorated.events;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.RemoteWebElement;
import ru.stqa.selenium.decorated.events.EventFiringWebDriver;
import ru.stqa.selenium.decorated.events.WebDriverListener;

public class EventFiringWebDriverTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EventFiringWebDriver eventFiringWebDriver0 = new EventFiringWebDriver((WebDriver) null);
      eventFiringWebDriver0.removeAllListeners();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EventFiringWebDriver eventFiringWebDriver0 = new EventFiringWebDriver((WebDriver) null);
      eventFiringWebDriver0.addListener((WebDriverListener) null);
      // Undeclared exception!
      try { 
        eventFiringWebDriver0.beforeMethodGlobal(eventFiringWebDriver0, (Method) null, (Object[]) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EventFiringWebDriver eventFiringWebDriver0 = new EventFiringWebDriver((WebDriver) null);
      eventFiringWebDriver0.removeListener((WebDriverListener) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EventFiringWebDriver eventFiringWebDriver0 = new EventFiringWebDriver((WebDriver) null);
      eventFiringWebDriver0.beforeMethodGlobal(eventFiringWebDriver0, (Method) null, (Object[]) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RemoteWebElement remoteWebElement0 = new RemoteWebElement();
      EventFiringWebDriver eventFiringWebDriver0 = new EventFiringWebDriver((WebDriver) null);
      eventFiringWebDriver0.afterMethodGlobal(eventFiringWebDriver0, (Method) null, remoteWebElement0, (Object[]) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RemoteWebElement remoteWebElement0 = new RemoteWebElement();
      EventFiringWebDriver eventFiringWebDriver0 = new EventFiringWebDriver((WebDriver) null);
      eventFiringWebDriver0.addListener((WebDriverListener) null);
      // Undeclared exception!
      try { 
        eventFiringWebDriver0.afterMethodGlobal(eventFiringWebDriver0, (Method) null, remoteWebElement0, (Object[]) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
