/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:00:59 GMT 2026
 */

package com.datascience.executor;

import org.junit.Test;
import static org.junit.Assert.*;
import com.datascience.executor.IExecutorCommand;
import com.datascience.executor.ProjectCommandExecutor;
import java.sql.SQLFeatureNotSupportedException;

public class ProjectCommandExecutorTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProjectCommandExecutor projectCommandExecutor0 = new ProjectCommandExecutor();
      projectCommandExecutor0.finalize();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProjectCommandExecutor projectCommandExecutor0 = new ProjectCommandExecutor(932);
      ProjectCommandExecutor.CommandCleaner projectCommandExecutor_CommandCleaner0 = projectCommandExecutor0.new CommandCleaner((IExecutorCommand) null);
      SQLFeatureNotSupportedException sQLFeatureNotSupportedException0 = new SQLFeatureNotSupportedException("G.[6", "G.[6");
      // Undeclared exception!
      try { 
        projectCommandExecutor_CommandCleaner0.onFailure(sQLFeatureNotSupportedException0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProjectCommandExecutor projectCommandExecutor0 = new ProjectCommandExecutor(932);
      projectCommandExecutor0.checkState();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ProjectCommandExecutor projectCommandExecutor0 = new ProjectCommandExecutor(18);
      projectCommandExecutor0.stop();
      // Undeclared exception!
      try { 
        projectCommandExecutor0.add((IExecutorCommand) null);
      } catch(IllegalStateException e) {
         //
         // Adding command after ProjectCommandExecutor was stopped
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ProjectCommandExecutor projectCommandExecutor0 = new ProjectCommandExecutor();
      boolean boolean0 = projectCommandExecutor0.canStop();
  }
}
