/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:36:24 GMT 2026
 */

package net.krotscheck.kangaroo.authz.common.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.URI;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.SortedMap;
import java.util.Stack;
import java.util.TreeMap;
import java.util.Vector;
import net.krotscheck.kangaroo.authz.common.authenticator.AuthenticatorType;
import net.krotscheck.kangaroo.authz.common.database.entity.ApplicationScope;
import net.krotscheck.kangaroo.authz.common.database.entity.Authenticator;
import net.krotscheck.kangaroo.authz.common.database.entity.Client;
import net.krotscheck.kangaroo.authz.common.database.entity.ClientRedirect;
import net.krotscheck.kangaroo.authz.common.database.entity.ClientType;
import net.krotscheck.kangaroo.authz.common.database.entity.Role;
import net.krotscheck.kangaroo.authz.common.util.ValidationUtil;
import net.krotscheck.kangaroo.authz.oauth2.exception.RFC6749;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.glassfish.jersey.uri.UriTemplate;

public class ValidationUtilTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Stack<ClientRedirect> stack0 = new Stack<ClientRedirect>();
      URI uRI0 = MockURI.aHttpURI;
      // Undeclared exception!
      try { 
        ValidationUtil.requireValidRedirect(uRI0, (List<ClientRedirect>) stack0);
      } catch(RFC6749.InvalidRequestException e) {
         //
         // invalid_request
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        ValidationUtil.validateResponseType((Client) null, "token");
      } catch(RFC6749.UnsupportedResponseTypeException e) {
         //
         // unsupported_response_type
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Client client0 = new Client();
      ClientType clientType0 = ClientType.Implicit;
      client0.setType(clientType0);
      // Undeclared exception!
      try { 
        ValidationUtil.validateResponseType(client0, ")0\"Bz!");
      } catch(RFC6749.UnsupportedResponseTypeException e) {
         //
         // unsupported_response_type
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ClientType clientType0 = ClientType.AuthorizationGrant;
      Client client0 = new Client();
      client0.setType(clientType0);
      ValidationUtil.validateResponseType(client0, "code");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Client client0 = new Client();
      ClientType clientType0 = ClientType.AuthorizationGrant;
      client0.setType(clientType0);
      // Undeclared exception!
      try { 
        ValidationUtil.validateResponseType(client0, ")0\"Bz!");
      } catch(RFC6749.UnsupportedResponseTypeException e) {
         //
         // unsupported_response_type
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stack<ClientRedirect> stack0 = new Stack<ClientRedirect>();
      ClientRedirect clientRedirect0 = new ClientRedirect();
      URI uRI0 = MockURI.URI("");
      clientRedirect0.setUri(uRI0);
      stack0.add(0, clientRedirect0);
      URI uRI1 = ValidationUtil.requireValidRedirect((URI) null, (List<ClientRedirect>) stack0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Stack<ClientRedirect> stack0 = new Stack<ClientRedirect>();
      ClientRedirect clientRedirect0 = new ClientRedirect();
      URI uRI0 = UriTemplate.normalize("org.bouncycastle.asn1.DefiniteLengthInputStream");
      clientRedirect0.setUri(uRI0);
      boolean boolean0 = stack0.add(clientRedirect0);
      URI uRI1 = ValidationUtil.requireValidRedirect((String) null, (List<ClientRedirect>) stack0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Stack<ClientRedirect> stack0 = new Stack<ClientRedirect>();
      // Undeclared exception!
      try { 
        ValidationUtil.requireValidRedirect((String) null, (List<ClientRedirect>) stack0);
      } catch(RFC6749.InvalidRequestException e) {
         //
         // invalid_request
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      URI uRI0 = MockURI.aHttpURI;
      HashSet<URI> hashSet0 = new HashSet<URI>();
      boolean boolean0 = hashSet0.add(uRI0);
      URI uRI1 = ValidationUtil.requireValidRedirect((String) null, (Set<URI>) hashSet0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<URI> linkedHashSet0 = new LinkedHashSet<URI>();
      URI uRI0 = ValidationUtil.validateRedirect((URI) null, (Set<URI>) linkedHashSet0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      URI uRI0 = MockURI.aHttpURI;
      LinkedHashSet<URI> linkedHashSet0 = new LinkedHashSet<URI>();
      boolean boolean0 = linkedHashSet0.add(uRI0);
      URI uRI1 = ValidationUtil.validateRedirect(uRI0, (Set<URI>) linkedHashSet0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      URI uRI0 = MockURI.aHttpURI;
      URI uRI1 = MockURI.URI("");
      LinkedHashSet<URI> linkedHashSet0 = new LinkedHashSet<URI>();
      boolean boolean0 = linkedHashSet0.add(uRI0);
      boolean boolean1 = linkedHashSet0.add(uRI1);
      URI uRI2 = ValidationUtil.validateRedirect(uRI1, (Set<URI>) linkedHashSet0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      URI uRI0 = MockURI.aHttpURI;
      HashSet<URI> hashSet0 = new HashSet<URI>();
      boolean boolean0 = hashSet0.add(uRI0);
      // Undeclared exception!
      try { 
        ValidationUtil.requireValidRedirect("6';[co4MWiaOTylTZ", (Set<URI>) hashSet0);
      } catch(RFC6749.InvalidRequestException e) {
         //
         // invalid_request
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedHashSet<URI> linkedHashSet0 = new LinkedHashSet<URI>();
      URI uRI0 = MockURI.create("+P@e?3D/]-4R0P]K,");
      boolean boolean0 = linkedHashSet0.add(uRI0);
      // Undeclared exception!
      try { 
        ValidationUtil.validateRedirect(uRI0, (Set<URI>) linkedHashSet0);
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.validateScope((String[]) null, (SortedMap<String, ApplicationScope>) treeMap0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.validateScope("^sZL", (SortedMap<String, ApplicationScope>) treeMap0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Role role0 = new Role();
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.validateScope(" ", role0);
      SortedMap<String, ApplicationScope> sortedMap1 = ValidationUtil.revalidateScope(" ", sortedMap0, sortedMap0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        ValidationUtil.validateScope("+#bbu", (SortedMap<String, ApplicationScope>) null);
      } catch(RFC6749.InvalidScopeException e) {
         //
         // invalid_scope
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      ApplicationScope applicationScope0 = new ApplicationScope();
      ApplicationScope applicationScope1 = treeMap0.put("^sZL", applicationScope0);
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.validateScope("^sZL", (SortedMap<String, ApplicationScope>) treeMap0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Role role0 = new Role();
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.validateScope((String) null, role0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      Role role0 = new Role();
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.validateScope((SortedMap<String, ApplicationScope>) treeMap0, role0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      // Undeclared exception!
      try { 
        ValidationUtil.validateScope((SortedMap<String, ApplicationScope>) treeMap0, (Role) null);
      } catch(RFC6749.InvalidScopeException e) {
         //
         // invalid_scope
         //
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      ApplicationScope applicationScope0 = new ApplicationScope();
      ApplicationScope applicationScope1 = treeMap0.put("^sZL", applicationScope0);
      Role role0 = new Role();
      // Undeclared exception!
      try { 
        ValidationUtil.validateScope((SortedMap<String, ApplicationScope>) treeMap0, role0);
      } catch(RFC6749.InvalidScopeException e) {
         //
         // invalid_scope
         //
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        ValidationUtil.validateScope(" ", (Role) null);
      } catch(RFC6749.InvalidScopeException e) {
         //
         // invalid_scope
         //
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      // Undeclared exception!
      try { 
        ValidationUtil.revalidateScope((String[]) null, (SortedMap<String, ApplicationScope>) null, (SortedMap<String, ApplicationScope>) null);
      } catch(RFC6749.InvalidScopeException e) {
         //
         // invalid_scope
         //
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      // Undeclared exception!
      try { 
        ValidationUtil.revalidateScope("e4M}K}PR8L=Nl", (SortedMap<String, ApplicationScope>) null, (SortedMap<String, ApplicationScope>) treeMap0);
      } catch(RFC6749.InvalidScopeException e) {
         //
         // invalid_scope
         //
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.revalidateScope((String[]) null, (SortedMap<String, ApplicationScope>) treeMap0, (SortedMap<String, ApplicationScope>) treeMap0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ApplicationScope applicationScope0 = new ApplicationScope();
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      ApplicationScope applicationScope1 = treeMap0.put("token", applicationScope0);
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.revalidateScope("token", (SortedMap<String, ApplicationScope>) treeMap0, (SortedMap<String, ApplicationScope>) treeMap0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ApplicationScope applicationScope0 = new ApplicationScope();
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      TreeMap<String, ApplicationScope> treeMap1 = new TreeMap<String, ApplicationScope>();
      ApplicationScope applicationScope1 = treeMap1.put("token", applicationScope0);
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.revalidateScope("token", (SortedMap<String, ApplicationScope>) treeMap1, (SortedMap<String, ApplicationScope>) treeMap0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      SortedMap<String, ApplicationScope> sortedMap0 = ValidationUtil.revalidateScope((String) null, (SortedMap<String, ApplicationScope>) treeMap0, (SortedMap<String, ApplicationScope>) treeMap0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Role role0 = new Role();
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      // Undeclared exception!
      try { 
        ValidationUtil.revalidateScope("[one of: '", (SortedMap<String, ApplicationScope>) treeMap0, role0);
      } catch(RFC6749.InvalidScopeException e) {
         //
         // invalid_scope
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TreeMap<String, ApplicationScope> treeMap0 = new TreeMap<String, ApplicationScope>();
      // Undeclared exception!
      try { 
        ValidationUtil.revalidateScope("", (SortedMap<String, ApplicationScope>) treeMap0, (Role) null);
      } catch(RFC6749.InvalidScopeException e) {
         //
         // invalid_scope
         //
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LinkedList<Authenticator> linkedList0 = new LinkedList<Authenticator>();
      Authenticator authenticator0 = new Authenticator();
      boolean boolean0 = linkedList0.add(authenticator0);
      AuthenticatorType authenticatorType0 = AuthenticatorType.Github;
      // Undeclared exception!
      try { 
        ValidationUtil.validateAuthenticator(authenticatorType0, linkedList0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      AuthenticatorType authenticatorType0 = AuthenticatorType.Google;
      Vector<Authenticator> vector0 = new Vector<Authenticator>();
      // Undeclared exception!
      try { 
        ValidationUtil.validateAuthenticator(authenticatorType0, vector0);
      } catch(RFC6749.InvalidRequestException e) {
         //
         // invalid_request
         //
      }
  }
}
