/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:34:43 GMT 2026
 */

package net.krotscheck.kangaroo.authz.admin.v1.resource;

import org.junit.Test;
import static org.junit.Assert.*;
import java.math.BigInteger;
import java.security.spec.RSAKeyGenParameterSpec;
import javax.ws.rs.NotFoundException;
import javax.ws.rs.core.UriInfo;
import net.krotscheck.kangaroo.authz.admin.v1.exception.EntityRequiredException;
import net.krotscheck.kangaroo.authz.admin.v1.resource.ClientRedirectService;
import net.krotscheck.kangaroo.authz.admin.v1.resource.OAuthTokenService;
import net.krotscheck.kangaroo.authz.admin.v1.resource.RoleScopeService;
import net.krotscheck.kangaroo.authz.admin.v1.resource.RoleService;
import net.krotscheck.kangaroo.authz.admin.v1.resource.ScopeService;
import net.krotscheck.kangaroo.authz.common.database.entity.AbstractAuthzEntity;
import net.krotscheck.kangaroo.authz.common.database.entity.Application;
import net.krotscheck.kangaroo.authz.common.database.entity.Client;
import net.krotscheck.kangaroo.authz.oauth2.authn.O2Principal;
import net.krotscheck.kangaroo.authz.oauth2.authn.O2SecurityContext;
import net.krotscheck.kangaroo.common.response.SortOrder;
import org.apache.commons.configuration.Configuration;
import org.bouncycastle.math.ec.ECConstants;
import org.glassfish.jersey.internal.inject.InjectionManager;
import org.glassfish.jersey.server.ContainerRequest;
import org.glassfish.jersey.server.internal.routing.UriRoutingContext;
import org.hibernate.Session;
import org.hibernate.search.FullTextQuery;
import org.hibernate.search.FullTextSession;
import org.hibernate.search.SearchFactory;

public class AbstractServiceTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      UriInfo uriInfo0 = oAuthTokenService0.getUriInfo();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      // Undeclared exception!
      try { 
        oAuthTokenService0.getAdminApplication();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      InjectionManager injectionManager0 = oAuthTokenService0.getInjector();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      Configuration configuration0 = oAuthTokenService0.getConfig();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ScopeService scopeService0 = new ScopeService();
      O2Principal o2Principal0 = new O2Principal();
      O2SecurityContext o2SecurityContext0 = new O2SecurityContext(o2Principal0);
      scopeService0.setSecurityContext(o2SecurityContext0);
      SortOrder sortOrder0 = SortOrder.ASC;
      BigInteger bigInteger0 = ECConstants.FOUR;
      // Undeclared exception!
      try { 
        scopeService0.browseScopes(1073775648, 1073775648, "", sortOrder0, bigInteger0, bigInteger0, bigInteger0);
      } catch(ClassCastException e) {
         //
         // net.krotscheck.kangaroo.authz.oauth2.authn.O2Principal cannot be cast to net.krotscheck.kangaroo.authz.common.database.entity.OAuthToken
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      oAuthTokenService0.setSearchFactory((SearchFactory) null);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ScopeService scopeService0 = new ScopeService();
      SortOrder sortOrder0 = SortOrder.ASC;
      BigInteger bigInteger0 = ECConstants.FOUR;
      // Undeclared exception!
      try { 
        scopeService0.browseScopes(1073775648, 1073775648, "", sortOrder0, bigInteger0, bigInteger0, bigInteger0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      UriRoutingContext uriRoutingContext0 = new UriRoutingContext((ContainerRequest) null);
      oAuthTokenService0.setUriInfo(uriRoutingContext0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      RoleService roleService0 = new RoleService();
      roleService0.setSession((Session) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      oAuthTokenService0.setFullTextSession((FullTextSession) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      SearchFactory searchFactory0 = oAuthTokenService0.getSearchFactory();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      oAuthTokenService0.setConfig((Configuration) null);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      RoleScopeService roleScopeService0 = new RoleScopeService();
      Class<Application> class0 = Application.class;
      // Undeclared exception!
      try { 
        roleScopeService0.executeQuery(class0, (FullTextQuery) null, 285282561, 285282561);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      FullTextSession fullTextSession0 = oAuthTokenService0.getFullTextSession();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      oAuthTokenService0.setInjector((InjectionManager) null);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Client client0 = new Client();
      RoleService roleService0 = new RoleService();
      // Undeclared exception!
      try { 
        roleService0.assertCanAccess(client0, "");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      RoleService roleService0 = new RoleService();
      // Undeclared exception!
      try { 
        roleService0.assertCanAccess((AbstractAuthzEntity) null, "");
      } catch(NotFoundException e) {
         //
         // HTTP 404 Not Found
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BigInteger bigInteger0 = BigInteger.TEN;
      Application application0 = new Application();
      ClientRedirectService clientRedirectService0 = new ClientRedirectService(bigInteger0);
      Class<Application> class0 = Application.class;
      // Undeclared exception!
      try { 
        clientRedirectService0.requireEntityInput(class0, application0);
      } catch(EntityRequiredException e) {
         //
         // An entity is required to complete this operation.
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BigInteger bigInteger0 = RSAKeyGenParameterSpec.F0;
      ClientRedirectService clientRedirectService0 = new ClientRedirectService(bigInteger0);
      Class<Application> class0 = Application.class;
      // Undeclared exception!
      try { 
        clientRedirectService0.requireEntityInput(class0, (Application) null);
      } catch(EntityRequiredException e) {
         //
         // An entity is required to complete this operation.
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      OAuthTokenService oAuthTokenService0 = new OAuthTokenService();
      Class<Application> class0 = Application.class;
      BigInteger bigInteger0 = ECConstants.EIGHT;
      // Undeclared exception!
      try { 
        oAuthTokenService0.resolveFilterEntity(class0, bigInteger0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
