/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:27:29 GMT 2026
 */

package io.airlift.airship.shared;

import org.junit.Test;
import static org.junit.Assert.*;
import io.airlift.airship.shared.MavenCoordinates;

public class TestMavenCoordinates {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"");
      String string0 = mavenCoordinates0.getVersion();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("HHp?_c;N};t@k#;\"", "sV7Q65q", "CharMatcher.or(", "HHp?_c;N};t@k#;\"", "CharMatcher.or(", "sV7Q65q");
      String string0 = mavenCoordinates0.getClassifier();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("Ab", "+=R9&K", "artifactId is null", "com.google.common.base.CharMatcher$15", "com.google.common.base.CharMatcher$15", (String) null);
      String string0 = mavenCoordinates0.getGroupId();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromGAV("@\"#xO`~{7B,*twE");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromBinaryGAV("@~7:d`T9r<{<q[");
      String string0 = MavenCoordinates.toBinaryGAV(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"", "HHp?_cN};@k#;\"");
      String string0 = mavenCoordinates0.getArtifactId();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("HHp?_c;N};t@k#;\"", "HHp?_c;N};t@k#;\"", "HHp?_c;N};t@k#;\"", "HHp?_c;N};t@k#;\"", "HHp?_c;N};t@k#;\"", "HHp?_c;N};t@k#;\"");
      String string0 = MavenCoordinates.toConfigGAV(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("CharMatcher.or(", "CharMatcher.or(", "CharMatcher.or(", "CharMatcher.or(", "CharMatcher.or(", "m");
      String string0 = mavenCoordinates0.getPackaging();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`CT9r<{<q[");
      String string0 = mavenCoordinates0.toString();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromBinaryGAV("The pattern may not match the empty string: %s");
      String string0 = mavenCoordinates0.toGAV();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("tar.gz");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromGAV("@~7:d`T9r<{<q[");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("config", "config", "tar.gz", "tar.gz", "@~7:d`T9r<{<q[", "@~7:d`T9r<{<q[");
      String string0 = MavenCoordinates.toBinaryGAV(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("HHp?_c;N};t@k#;\"", "HHp?_c;N};t@k#;\"", "CharMatcher.or(", "HHp?_c;N};t@k#;\"", "CharMatcher.or(", "HHp?_c;N};t@k#;\"");
      String string0 = mavenCoordinates0.toString();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromBinaryGAV("@~7:d`T9r<{<q[");
      String string0 = mavenCoordinates0.getFileVersion();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("HHp?_c;N};t@k#;\"", "HHp?_c;N};t@k#;\"", "CharMatcher.or(", "HHp?_c;N};t@k#;\"", "CharMatcher.or(", "HHp?_c;N};t@k#;\"");
      String string0 = mavenCoordinates0.getFileVersion();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`T9<{<q[");
      boolean boolean0 = mavenCoordinates0.isResolved();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("jGm6", "~7", "I%5bm`", "a^=\"", "~7", "a^=\"");
      boolean boolean0 = mavenCoordinates0.isResolved();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("Ab", "+=R9&K", "artifactId is null", "com.google.common.base.CharMatcher$15", "com.google.common.base.CharMatcher$15", (String) null);
      boolean boolean0 = mavenCoordinates0.isResolved();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`Cv9r<{<q");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("jGm6", "~7", "I%5bm`", "a^=\"", "~7", "a^=\"");
      boolean boolean0 = mavenCoordinates0.equalsIgnoreVersion(mavenCoordinates1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`T9r<{<q[");
      boolean boolean0 = mavenCoordinates0.equalsIgnoreVersion(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromBinaryGAV("@~7:d`T9r<{<q[");
      boolean boolean0 = mavenCoordinates0.equalsIgnoreVersion((MavenCoordinates) null);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`T9r<{<q[");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("config", "config", "tar.gz", "tar.gz", "@~7:d`T9r<{<q[", "@~7:d`T9r<{<q[");
      boolean boolean0 = mavenCoordinates1.equalsIgnoreVersion(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("@\"#xO`~{7B,*twE", "config", "config", "config", "tar.gz", "@\"#xO`~{7B,*twE");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("@\"#xO`~{7B,*twE", "config", "tar.gz", "tar.gz", "tar.gz", "config");
      boolean boolean0 = mavenCoordinates1.equalsIgnoreVersion(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("The patteA maynnot match the hmty strng:%s", "The patteA maynnot match the hmty strng:%s", "The patteA maynnot match the hmty strng:%s", "The patteA maynnot match the hmty strng:%s", "The patteA maynnot match the hmty strng:%s", "The patteA maynnot match the hmty strng:%s");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("tar.gz", "The patteA maynnot match the hmty strng:%s", "tar.gz", "tar.gz", "config", "The patteA maynnot match the hmty strng:%s");
      boolean boolean0 = mavenCoordinates0.equalsIgnoreVersion(mavenCoordinates1);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`T9r<{<q[");
      MavenCoordinates mavenCoordinates1 = MavenCoordinates.fromConfigGAV("@~7:d`T9r<{<q[");
      boolean boolean0 = mavenCoordinates1.equalsIgnoreVersion(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("&15N#4Ow_/2Vv1.", "config", "config", "config", "tar.gz", "@\"#xO`~{7B,*twE");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("@\"#xO`~{7B,*twE", "config", "tar.gz", "tar.gz", "tar.gz", "config");
      boolean boolean0 = mavenCoordinates0.equalsIgnoreVersion(mavenCoordinates1);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`Cv9r<{<q");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("jGm6", "~7", "I%5bm`", "a^=\"", "~7", "a^=\"");
      boolean boolean0 = mavenCoordinates0.equals(mavenCoordinates1);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`T9r<{<q[");
      boolean boolean0 = mavenCoordinates0.equals(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromBinaryGAV("@~7:d`T9r<{<q[");
      boolean boolean0 = mavenCoordinates0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromBinaryGAV("The pattern may not match the empty string: %s");
      boolean boolean0 = mavenCoordinates0.equals("The pattern may not match the empty string: %s");
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("@~7:d`CT9r<{<q[", "@~7:d`CT9r<{<q[", "@~7:d`CT9r<{<q[", "@~7:d`CT9r<{<q[", "@~7:d`CT9r<{<q[", "@~7:d`CT9r<{<q[");
      MavenCoordinates mavenCoordinates1 = MavenCoordinates.fromConfigGAV("@~7:d`CT9r<{<q[");
      boolean boolean0 = mavenCoordinates1.equals(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("config", "config", "config", "@Bom.google.common.base.ChsrMatcher$15", "tar.gz", "@\"#xO`~{7B,*twE");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("@\"#xO`~{7B,*twE", "config", "tar.gz", "tar.gz", "{_@4<)uq8Qr&", "config");
      boolean boolean0 = mavenCoordinates1.equals(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("The pattern may not match thM empty strin5:%s", "The pattern may not match thM empty strin5:%s", "The pattern may not match thM empty strin5:%s", "The pattern may not match thM empty strin5:%s", "The pattern may not match thM empty strin5:%s", "The pattern may not match thM empty strin5:%s");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("The pattern may not match thM empty strin5:%s", "The pattern may not match thM empty strin5:%s", "The pattern may not match thM empty strin5:%s", "config", "The pattern may not match thM empty strin5:%s", "tar.gz");
      boolean boolean0 = mavenCoordinates1.equals(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`T9r<{<q[");
      MavenCoordinates mavenCoordinates1 = MavenCoordinates.fromConfigGAV("@~7:d`T9r<{<q[");
      boolean boolean0 = mavenCoordinates1.equals(mavenCoordinates0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("tar.gz", "config", "config", "config", "tar.gz", "@\"#xO`~{7B,*twE");
      MavenCoordinates mavenCoordinates1 = new MavenCoordinates("@\"#xO`~{7B,*twE", "config", "tar.gz", "tar.gz", "tar.gz", "config");
      boolean boolean0 = mavenCoordinates0.equals(mavenCoordinates1);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = MavenCoordinates.fromConfigGAV("@~7:d`T9r<{<q[");
      int int0 = mavenCoordinates0.hashCode();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("Ab", "+=R9&K", "artifactId is null", "com.google.common.base.CharMatcher$15", "com.google.common.base.CharMatcher$15", (String) null);
      int int0 = mavenCoordinates0.hashCode();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MavenCoordinates mavenCoordinates0 = new MavenCoordinates("@\"#xO`~{7B,*twE", "@\"#xO`~{7B,*twE", "@\"#xO`~{7B,*twE", "@\"#xO`~{7B,*twE", "@\"#xO`~{7B,*twE", "@\"#xO`~{7B,*twE");
      int int0 = mavenCoordinates0.hashCode();
  }
}
