/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:25:36 GMT 2026
 */

package io.airlift.airship.coordinator;

import org.junit.Test;
import static org.junit.Assert.*;
import io.airlift.airship.coordinator.AdminResource;
import io.airlift.airship.coordinator.AgentProvisioningRepresentation;
import io.airlift.airship.coordinator.Coordinator;
import io.airlift.airship.coordinator.CoordinatorProvisioningRepresentation;
import io.airlift.airship.shared.Repository;
import javax.ws.rs.core.UriInfo;

public class TestAdminResource {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdminResource adminResource0 = new AdminResource((Coordinator) null, (Repository) null);
      try { 
        adminResource0.provisionCoordinator((CoordinatorProvisioningRepresentation) null, (UriInfo) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AdminResource adminResource0 = new AdminResource((Coordinator) null, (Repository) null);
      // Undeclared exception!
      try { 
        adminResource0.getAllAgents((UriInfo) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AdminResource adminResource0 = new AdminResource((Coordinator) null, (Repository) null);
      try { 
        adminResource0.provisionAgent((AgentProvisioningRepresentation) null, (UriInfo) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AdminResource adminResource0 = new AdminResource((Coordinator) null, (Repository) null);
      // Undeclared exception!
      try { 
        adminResource0.getAllCoordinators((UriInfo) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
