/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 03:14:47 GMT 2026
 */

package io.opentracing.contrib.mongo.common.providers;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mongodb.ServerAddress;
import com.mongodb.connection.ClusterId;
import com.mongodb.connection.ConnectionDescription;
import com.mongodb.connection.ConnectionId;
import com.mongodb.connection.ServerId;
import com.mongodb.connection.ServerType;
import com.mongodb.event.CommandStartedEvent;
import io.opentracing.contrib.mongo.common.providers.NoopSpanNameProvider;
import java.util.Stack;
import org.bson.BsonDocumentWrapper;
import org.bson.codecs.IntegerCodec;

public class NoopSpanNameProviderTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoopSpanNameProvider noopSpanNameProvider0 = new NoopSpanNameProvider();
      String string0 = noopSpanNameProvider0.generateName((CommandStartedEvent) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NoopSpanNameProvider noopSpanNameProvider0 = new NoopSpanNameProvider();
      ClusterId clusterId0 = new ClusterId();
      ServerAddress serverAddress0 = new ServerAddress("");
      ServerId serverId0 = new ServerId(clusterId0, serverAddress0);
      ConnectionId connectionId0 = new ConnectionId(serverId0);
      ServerType serverType0 = ServerType.STANDALONE;
      Stack<String> stack0 = new Stack<String>();
      ConnectionDescription connectionDescription0 = new ConnectionDescription(connectionId0, 0, serverType0, 2674, 0, 0, stack0);
      Integer integer0 = new Integer(0);
      IntegerCodec integerCodec0 = new IntegerCodec();
      BsonDocumentWrapper<Integer> bsonDocumentWrapper0 = new BsonDocumentWrapper<Integer>(integer0, integerCodec0);
      CommandStartedEvent commandStartedEvent0 = new CommandStartedEvent(41, connectionDescription0, "ClusterId{value='52fe7ac1000001000100004d', description='null'}", (String) null, bsonDocumentWrapper0);
      String string0 = noopSpanNameProvider0.generateName(commandStartedEvent0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NoopSpanNameProvider noopSpanNameProvider0 = new NoopSpanNameProvider();
      ClusterId clusterId0 = new ClusterId();
      ServerAddress serverAddress0 = new ServerAddress();
      ServerId serverId0 = new ServerId(clusterId0, serverAddress0);
      ConnectionDescription connectionDescription0 = new ConnectionDescription(serverId0);
      Integer integer0 = new Integer(0);
      IntegerCodec integerCodec0 = new IntegerCodec();
      BsonDocumentWrapper<Integer> bsonDocumentWrapper0 = new BsonDocumentWrapper<Integer>(integer0, integerCodec0);
      CommandStartedEvent commandStartedEvent0 = new CommandStartedEvent(0, connectionDescription0, ".*", ".*", bsonDocumentWrapper0);
      String string0 = noopSpanNameProvider0.generateName(commandStartedEvent0);
  }
}
