/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 03:14:09 GMT 2026
 */

package org.jdesktop.core.animation.timing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.CopyOnWriteArraySet;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.lang.MockThread;
import org.jdesktop.core.animation.timing.Animator;
import org.jdesktop.core.animation.timing.TimingSource;
import org.jdesktop.core.animation.timing.TimingTarget;
import org.jdesktop.core.animation.timing.interpolators.DiscreteInterpolator;
import org.jdesktop.core.animation.timing.sources.ManualTimingSource;
import org.jdesktop.core.animation.timing.sources.ScheduledExecutorTimingSource;

public class TestTimingSource {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeUnit timeUnit0 = TimeUnit.SECONDS;
      ScheduledExecutorTimingSource scheduledExecutorTimingSource0 = new ScheduledExecutorTimingSource(0L, timeUnit0);
      ManualTimingSource manualTimingSource0 = new ManualTimingSource();
      Animator.EndBehavior animator_EndBehavior0 = Animator.EndBehavior.RESET;
      DiscreteInterpolator discreteInterpolator0 = DiscreteInterpolator.getInstance();
      Animator.RepeatBehavior animator_RepeatBehavior0 = Animator.RepeatBehavior.LOOP;
      Animator.Direction animator_Direction0 = Animator.Direction.BACKWARD;
      ConcurrentLinkedQueue<TimingTarget> concurrentLinkedQueue0 = new ConcurrentLinkedQueue<TimingTarget>();
      Animator animator0 = new Animator("fFpeGFJnO4D4i", (-2687L), timeUnit0, animator_EndBehavior0, discreteInterpolator0, animator_RepeatBehavior0, (-1323L), animator_Direction0, (-1323L), timeUnit0, scheduledExecutorTimingSource0, true, concurrentLinkedQueue0);
      manualTimingSource0.removeTickListener(animator0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ManualTimingSource manualTimingSource0 = new ManualTimingSource();
      TimingSource.PostTickListener timingSource_PostTickListener0 = mock(TimingSource.PostTickListener.class, new ViolatedAssumptionAnswer());
      manualTimingSource0.removePostTickListener(timingSource_PostTickListener0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeUnit timeUnit0 = TimeUnit.HOURS;
      ScheduledExecutorTimingSource scheduledExecutorTimingSource0 = new ScheduledExecutorTimingSource((-1L), timeUnit0);
      Animator.EndBehavior animator_EndBehavior0 = Animator.EndBehavior.HOLD;
      DiscreteInterpolator discreteInterpolator0 = DiscreteInterpolator.getInstance();
      Animator.RepeatBehavior animator_RepeatBehavior0 = Animator.RepeatBehavior.LOOP;
      Animator.Direction animator_Direction0 = Animator.Direction.BACKWARD;
      CopyOnWriteArraySet<TimingTarget> copyOnWriteArraySet0 = new CopyOnWriteArraySet<TimingTarget>();
      Animator animator0 = new Animator("", 507L, timeUnit0, animator_EndBehavior0, discreteInterpolator0, animator_RepeatBehavior0, 2053L, animator_Direction0, (-868L), timeUnit0, scheduledExecutorTimingSource0, false, copyOnWriteArraySet0);
      scheduledExecutorTimingSource0.addTickListener(animator0);
      scheduledExecutorTimingSource0.runPerTick();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ManualTimingSource manualTimingSource0 = new ManualTimingSource();
      manualTimingSource0.addTickListener((TimingSource.TickListener) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ScheduledExecutorTimingSource scheduledExecutorTimingSource0 = new ScheduledExecutorTimingSource();
      scheduledExecutorTimingSource0.addPostTickListener((TimingSource.PostTickListener) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ManualTimingSource manualTimingSource0 = new ManualTimingSource();
      MockThread mockThread0 = new MockThread();
      manualTimingSource0.submit(mockThread0);
      manualTimingSource0.runPerTick();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ScheduledExecutorTimingSource scheduledExecutorTimingSource0 = new ScheduledExecutorTimingSource();
      scheduledExecutorTimingSource0.submit((Runnable) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ManualTimingSource manualTimingSource0 = new ManualTimingSource();
      TimingSource.PostTickListener timingSource_PostTickListener0 = mock(TimingSource.PostTickListener.class, new ViolatedAssumptionAnswer());
      manualTimingSource0.addPostTickListener(timingSource_PostTickListener0);
      manualTimingSource0.runPerTick();
  }
}
