/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 01:54:45 GMT 2026
 */

package ca.uhn.fhir.util;

import org.junit.Test;
import static org.junit.Assert.*;
import ca.uhn.fhir.util.UrlUtil;

public class UrlUtilTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      UrlUtil urlUtil0 = new UrlUtil();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = UrlUtil.constructAbsoluteUrl((String) null, "!");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = UrlUtil.constructAbsoluteUrl((String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = UrlUtil.constructAbsoluteUrl("https://", "https://");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = UrlUtil.constructAbsoluteUrl("", "");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      boolean boolean0 = UrlUtil.isAbsolute("http://htts://p,8%");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = UrlUtil.constructRelativeUrl("https:/", "http://");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = UrlUtil.constructRelativeUrl((String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = UrlUtil.constructRelativeUrl("https://", (String) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = UrlUtil.constructRelativeUrl("-q%yG&iZ8", "-q%yG&iZ8");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = UrlUtil.constructRelativeUrl("https://", "K{(vUGAVyZG3bAKmkH");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = UrlUtil.constructRelativeUrl("https://", "yr/&Zr4Q&%m0");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = UrlUtil.constructRelativeUrl("https://", "https://");
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid((String) null);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("h.sH;gR//");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("QolGYLc");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("inI|GLYFo(NjSF");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("http%://");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("htp://htts://p,8%");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("httS://tts//p,8%");
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("http://htts://p,8%");
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("httpsr://");
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("https:7O/");
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      boolean boolean0 = UrlUtil.isValid("http:/O/%tts:/Qf,8%");
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      // Undeclared exception!
      try { 
        UrlUtil.unescape("-q%yGw&iZ8");
      } catch(IllegalArgumentException e) {
         //
         // URLDecoder: Illegal hex characters in escape (%) pattern - For input string: \"y\"
         //
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String string0 = UrlUtil.unescape((String) null);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      String string0 = UrlUtil.unescape("");
  }
}
