/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:53:19 GMT 2026
 */

package flapjack.cobol.layout;

import org.junit.Test;
import static org.junit.Assert.*;
import flapjack.cobol.layout.CobolFieldDefinition;
import flapjack.cobol.layout.CobolFieldDefinitionFactory;
import flapjack.cobol.layout.CobolFieldInfo;
import flapjack.cobol.layout.CobolFieldType;
import flapjack.layout.NoOpPaddingDescriptor;
import flapjack.layout.TextPaddingDescriptor;

public class CobolFieldDefinitionFactoryTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CobolFieldDefinitionFactory cobolFieldDefinitionFactory0 = new CobolFieldDefinitionFactory();
      CobolFieldInfo cobolFieldInfo0 = new CobolFieldInfo();
      TextPaddingDescriptor.Padding textPaddingDescriptor_Padding0 = TextPaddingDescriptor.Padding.NONE;
      TextPaddingDescriptor textPaddingDescriptor0 = new TextPaddingDescriptor(textPaddingDescriptor_Padding0, '5');
      // Undeclared exception!
      try { 
        cobolFieldDefinitionFactory0.build(cobolFieldInfo0, textPaddingDescriptor0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CobolFieldDefinitionFactory cobolFieldDefinitionFactory0 = new CobolFieldDefinitionFactory();
      CobolFieldInfo cobolFieldInfo0 = new CobolFieldInfo("flapjack.cobol.layout.CobolFieldDefinitionFactory", ",y'0-R<gvE1LT");
      CobolFieldType cobolFieldType0 = CobolFieldType.DECIMAL;
      cobolFieldInfo0.setType(cobolFieldType0);
      NoOpPaddingDescriptor noOpPaddingDescriptor0 = new NoOpPaddingDescriptor();
      CobolFieldDefinition cobolFieldDefinition0 = cobolFieldDefinitionFactory0.build(cobolFieldInfo0, noOpPaddingDescriptor0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CobolFieldDefinitionFactory cobolFieldDefinitionFactory0 = new CobolFieldDefinitionFactory();
      CobolFieldInfo cobolFieldInfo0 = new CobolFieldInfo();
      TextPaddingDescriptor.Padding textPaddingDescriptor_Padding0 = TextPaddingDescriptor.Padding.NONE;
      TextPaddingDescriptor textPaddingDescriptor0 = new TextPaddingDescriptor(textPaddingDescriptor_Padding0, '5');
      CobolFieldType cobolFieldType0 = CobolFieldType.INTEGER;
      cobolFieldInfo0.setType(cobolFieldType0);
      // Undeclared exception!
      try { 
        cobolFieldDefinitionFactory0.build(cobolFieldInfo0, textPaddingDescriptor0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
