/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:22:08 GMT 2026
 */

package com.googlecode.fitchy;

import org.junit.Test;
import static org.junit.Assert.*;
import com.googlecode.fitchy.Configuration;
import com.googlecode.fitchy.Feature;
import com.googlecode.fitchy.FeatureContext;
import com.googlecode.fitchy.FeatureStatus;
import com.googlecode.fitchy.internal.DefaultFeatureStatus;
import java.io.ByteArrayInputStream;
import java.io.FileDescriptor;
import java.net.URI;
import java.net.URL;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;

public class FeatureContextTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, (-1), (-1));
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.fromStream(byteArrayInputStream0);
      FeatureContext featureContext0 = featureContext_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      URI uRI0 = MockURI.aFileURI;
      URL uRL0 = MockURI.toURL(uRI0);
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.fromUrl(uRL0);
      FeatureContext featureContext0 = featureContext_Builder0.build();
      Configuration configuration0 = Configuration.getDefault();
      Feature feature0 = new Feature("(za", configuration0.enabledStatus);
      Feature feature1 = featureContext0.addFeature(feature0);
      DefaultFeatureStatus defaultFeatureStatus0 = (DefaultFeatureStatus)configuration0.enabledStatus;
      boolean boolean0 = featureContext0.featureHasStatus("(za", defaultFeatureStatus0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Configuration configuration0 = new Configuration();
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.fromStream(mockFileInputStream0);
      FeatureContext.Builder featureContext_Builder1 = featureContext_Builder0.withConfig(configuration0);
      FeatureContext featureContext0 = featureContext_Builder1.build();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FeatureContext featureContext0 = new FeatureContext((Configuration) null);
      int int0 = featureContext0.size();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.create();
      FeatureContext featureContext0 = featureContext_Builder0.createEmpty();
      featureContext0.clear();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.create();
      FeatureContext featureContext0 = featureContext_Builder0.build();
      // Undeclared exception!
      try { 
        featureContext0.addFeature((String) null);
      } catch(IllegalArgumentException e) {
         //
         // key argument must be a value
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("tmp\\foo.bar");
      boolean boolean0 = FileSystemHandling.appendLineToFile(evoSuiteFile0, "URL argument is required to create context");
      URI uRI0 = MockURI.aFileURI;
      URL uRL0 = MockURI.toURL(uRI0);
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.fromUrl(uRL0);
      FeatureContext featureContext0 = featureContext_Builder0.build();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Configuration configuration0 = Configuration.getDefault();
      FeatureContext featureContext0 = new FeatureContext(configuration0);
      Feature feature0 = featureContext0.addFeature("W~bZFNp%noJL");
      // Undeclared exception!
      try { 
        featureContext0.addFeature(feature0);
      } catch(RuntimeException e) {
         //
         // feature with name W~bZFNp%noJL already exists.
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Configuration configuration0 = Configuration.getDefault();
      FeatureContext featureContext0 = new FeatureContext(configuration0);
      // Undeclared exception!
      try { 
        featureContext0.addFeature("");
      } catch(IllegalArgumentException e) {
         //
         // key argument must be a value
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      URL uRL0 = MockURL.getFtpExample();
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.fromUrl(uRL0);
      FeatureContext featureContext0 = featureContext_Builder0.createEmpty();
      Feature feature0 = featureContext0.addFeature("vY");
      // Undeclared exception!
      try { 
        featureContext0.addFeature("vY");
      } catch(RuntimeException e) {
         //
         // feature with name vY already exists.
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.create();
      FeatureContext featureContext0 = featureContext_Builder0.build();
      // Undeclared exception!
      try { 
        featureContext0.addFeature((Feature) null);
      } catch(IllegalArgumentException e) {
         //
         // feature argument must be an instance
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Configuration configuration0 = new Configuration();
      FeatureContext featureContext0 = new FeatureContext(configuration0);
      boolean boolean0 = featureContext0.hasFeature((String) null);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Configuration configuration0 = Configuration.getDefault();
      FeatureContext featureContext0 = new FeatureContext(configuration0);
      Feature feature0 = new Feature("", configuration0.disabledStatus);
      Feature feature1 = featureContext0.addFeature(feature0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.create();
      FeatureContext featureContext0 = featureContext_Builder0.build();
      // Undeclared exception!
      try { 
        featureContext0.featureHasStatus((String) null, (FeatureStatus) null);
      } catch(IllegalArgumentException e) {
         //
         // key argument is required
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      URI uRI0 = MockURI.aFileURI;
      URL uRL0 = MockURI.toURL(uRI0);
      FeatureContext.Builder featureContext_Builder0 = FeatureContext.Builder.fromUrl(uRL0);
      FeatureContext featureContext0 = featureContext_Builder0.build();
      Configuration configuration0 = Configuration.getDefault();
      DefaultFeatureStatus defaultFeatureStatus0 = (DefaultFeatureStatus)configuration0.enabledStatus;
      boolean boolean0 = featureContext0.featureHasStatus("(za", defaultFeatureStatus0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Configuration configuration0 = Configuration.getDefault();
      FeatureContext featureContext0 = new FeatureContext(configuration0);
      // Undeclared exception!
      try { 
        featureContext0.featureHasStatus("", configuration0.enabledStatus);
      } catch(IllegalArgumentException e) {
         //
         // key argument is required
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Configuration configuration0 = Configuration.getDefault();
      FeatureContext featureContext0 = new FeatureContext(configuration0);
      Feature feature0 = featureContext0.addFeature("W~bZFNp%noJL");
      boolean boolean0 = featureContext0.featureHasStatus("W~bZFNp%noJL", configuration0.disabledStatus);
  }
}
