/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 03:22:33 GMT 2026
 */

package com.anjlab.sat3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.anjlab.sat3.Helper;
import com.anjlab.sat3.ITier;
import com.anjlab.sat3.ITripletValue;
import com.anjlab.sat3.SimpleTier;
import com.anjlab.sat3.SimpleTriplet;
import com.anjlab.sat3.Value;
import java.util.function.Consumer;
import org.evosuite.runtime.ViolatedAssumptionAnswer;

public class TestSimpleTier {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(133, (-965), 14);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      simpleTriplet0.forEach(consumer0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(4323, (-1181), 1850);
      simpleTriplet0.union(simpleTriplet0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(30, 7, 535481);
      simpleTriplet0.intersect((ITier) simpleTriplet0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(669, 515, 17);
      simpleTriplet0.remove(simpleTriplet0);
      Value value0 = simpleTriplet0.valueOfB();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleTier simpleTier0 = null;
      try {
        simpleTier0 = new SimpleTier(1082, 133, (-141));
      } catch(IllegalArgumentException e) {
         //
         // a <= 0 || b <= 0 || c <= 0 (
         // VarCount: 3; ClausesCount: 0; TiersCount: 1)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-965), (-910), 2889);
      simpleTriplet0.adjoinRight(simpleTriplet0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(4323, (-1181), 1850);
      SimpleTier simpleTier0 = (SimpleTier)simpleTriplet0.clone();
      Value value0 = Value.AllNegative;
      simpleTriplet0.concretize(4323, value0);
      boolean boolean0 = simpleTier0.equals(simpleTriplet0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(158, 114, (-338));
      simpleTriplet0.add(simpleTriplet0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-964), 311, 2890);
      ITripletValue iTripletValue0 = simpleTriplet0.getAdjoinLeftSource1();
      simpleTriplet0.add(iTripletValue0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(7, 2875, 637);
      ITripletValue iTripletValue0 = simpleTriplet0.getAdjoinLeftSource2();
      simpleTriplet0.remove(iTripletValue0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(133, (-965), 14);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      simpleTriplet0.inverse();
      simpleTriplet0.forEach(consumer0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(7, 2875, 637);
      simpleTriplet0.swapAB();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SimpleTier simpleTier0 = new SimpleTier(34, 492, 120);
      simpleTier0.swapAB();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-965), 311, 2890);
      simpleTriplet0.swapAC();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SimpleTier simpleTier0 = new SimpleTier(34, 492, 120);
      simpleTier0.swapAC();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(88, 741, (-1532));
      simpleTriplet0.swapBC();
      Value value0 = simpleTriplet0.valueOfB();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(17, 370, 97);
      ITripletValue iTripletValue0 = simpleTriplet0.getAdjoinRightTarget2();
      simpleTriplet0.intersect(iTripletValue0);
      simpleTriplet0.swapBC();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SimpleTier simpleTier0 = SimpleTier.createCompleteTier(244745, 1759, 1102);
      boolean boolean0 = simpleTier0.isEmpty();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SimpleTier simpleTier0 = new SimpleTier(3, 244746, 1106);
      boolean boolean0 = simpleTier0.isEmpty();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(10, 2125, 656423);
      Helper.EnableAssertions = false;
      Value value0 = Value.AllPlain;
      simpleTriplet0.concretize(10, value0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(4323, (-1181), 1850);
      Value value0 = Value.AllNegative;
      simpleTriplet0.concretize(4323, value0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-965), 330, 2890);
      Value value0 = Value.AllPlain;
      simpleTriplet0.concretize(330, value0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(19, 980, 1490);
      Value value0 = Value.Mixed;
      // Undeclared exception!
      try { 
        simpleTriplet0.concretize(19, value0);
      } catch(IllegalArgumentException e) {
         //
         // Value should be one of (AllPlain, AllNegative) but was Mixed
         //
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-965), (-910), 2890);
      Value value0 = Value.AllNegative;
      simpleTriplet0.concretize(2890, value0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(19, 980, 1490);
      Value value0 = Value.AllNegative;
      simpleTriplet0.concretize(980, value0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(311, (-1883), 1181);
      Value value0 = Value.AllNegative;
      // Undeclared exception!
      try { 
        simpleTriplet0.concretize((-1883), value0);
      } catch(IllegalArgumentException e) {
         //
         // Can't concretize tier on varName=-1883 because varName is not from the tier's permutation
         //
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(19, 980, 1490);
      Value value0 = Value.AllPlain;
      simpleTriplet0.concretize(1490, value0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-2703), (-1419), 128);
      Value value0 = simpleTriplet0.valueOfA();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(93, 1744, 31);
      simpleTriplet0.remove(simpleTriplet0);
      Value value0 = simpleTriplet0.valueOfA();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(965, 4387, 2894);
      Value value0 = simpleTriplet0.valueOfA();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(965, 4387, 2894);
      simpleTriplet0.inverse();
      Value value0 = simpleTriplet0.valueOfA();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(88, 741, (-1532));
      Value value0 = simpleTriplet0.valueOfB();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(88, 741, (-1532));
      simpleTriplet0.inverse();
      Value value0 = simpleTriplet0.valueOfB();
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(2473, 7, (-552));
      Value value0 = simpleTriplet0.valueOfC();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-1244), 48, (-3336));
      simpleTriplet0.adjoinLeft(simpleTriplet0);
      Value value0 = simpleTriplet0.valueOfC();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SimpleTier simpleTier0 = SimpleTier.createCompleteTier(244703, 1744, 1077);
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(1744, 204, 1077);
      simpleTier0.intersect((ITripletValue) simpleTriplet0);
      Value value0 = simpleTier0.valueOfC();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      SimpleTier simpleTier0 = SimpleTier.createCompleteTier(244703, 1744, 1106);
      Value value0 = simpleTier0.valueOfC();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet(4323, (-1181), 1850);
      boolean boolean0 = simpleTriplet0.equals(simpleTriplet0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-965), 17, 2894);
      boolean boolean0 = simpleTriplet0.equals("\nVarCount: 3; ClausesCount: 1; TiersCount: 1");
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      SimpleTriplet simpleTriplet0 = new SimpleTriplet((-965), (-5302), (-914));
      SimpleTriplet simpleTriplet1 = new SimpleTriplet((-5302), (-965), (-914));
      boolean boolean0 = simpleTriplet0.equals(simpleTriplet1);
  }
}
