/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 03:10:08 GMT 2026
 */

package com.salesforce.pyplyn.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.salesforce.pyplyn.util.FormatUtils;
import java.text.ParseException;
import java.time.format.DateTimeParseException;

public class FormatUtilsTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        FormatUtils.parseUTCTime("\"m]l)");
      } catch(DateTimeParseException e) {
         //
         // Text '\"m]l)' could not be parsed at index 0
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Float float0 = new Float((-41.7));
      String string0 = FormatUtils.generateDefaultValueMessage("AZ>|B[srC=dU@a", float0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      try { 
        FormatUtils.parseNumber("");
      } catch(ParseException e) {
         //
         // Unparseable number: \"\"
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Float float0 = new Float(0.0);
      String string0 = FormatUtils.formatNumberFiveCharLimit(float0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Float float0 = new Float(2364.382941);
      String string0 = FormatUtils.formatNumberFiveCharLimit(float0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Float float0 = new Float((-527.674845919));
      String string0 = FormatUtils.formatNumberFiveCharLimit(float0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Float float0 = new Float(5717.065F);
      String string0 = FormatUtils.formatMillisOrSeconds(float0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Long long0 = new Long(0L);
      String string0 = FormatUtils.formatMillisOrSeconds(long0);
  }
}
