/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:03:22 GMT 2026
 */

package com.google.cloud.runtimes.tomcat.session;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.cloud.runtimes.tomcat.session.DatastoreManager;
import org.apache.catalina.Session;
import org.apache.catalina.Store;
import org.apache.catalina.session.FileStore;

public class DatastoreManagerTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      // Undeclared exception!
      try { 
        datastoreManager0.remove((Session) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      // Undeclared exception!
      try { 
        datastoreManager0.getActiveSessionsFull();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      // Undeclared exception!
      try { 
        datastoreManager0.getSessionIdsFull();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      datastoreManager0.load();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      datastoreManager0.unload();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      Session session0 = datastoreManager0.createEmptySession();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      FileStore fileStore0 = new FileStore();
      datastoreManager0.setStore(fileStore0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      // Undeclared exception!
      try { 
        datastoreManager0.findSession("CharMatcher.none()");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      FileStore fileStore0 = new FileStore();
      datastoreManager0.store = (Store) fileStore0;
      try { 
        datastoreManager0.startInternal();
      } catch(Exception e) {
         //
         // An invalid Lifecycle transition was attempted ([STARTING]) for component [com.google.cloud.runtimes.tomcat.session.DatastoreManager@0000000001] in state [NEW]
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      try { 
        datastoreManager0.startInternal();
      } catch(Exception e) {
         //
         // No Store configured, persistence disabled
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      try { 
        datastoreManager0.stopInternal();
      } catch(Exception e) {
         //
         // An invalid Lifecycle transition was attempted ([STOPPING]) for component [com.google.cloud.runtimes.tomcat.session.DatastoreManager@0000000001] in state [NEW]
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      FileStore fileStore0 = new FileStore();
      datastoreManager0.store = (Store) fileStore0;
      try { 
        datastoreManager0.stopInternal();
      } catch(Exception e) {
         //
         // An invalid Lifecycle transition was attempted ([STOPPING]) for component [com.google.cloud.runtimes.tomcat.session.DatastoreManager@0000000001] in state [NEW]
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      datastoreManager0.processExpires();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DatastoreManager datastoreManager0 = new DatastoreManager();
      FileStore fileStore0 = new FileStore();
      datastoreManager0.store = (Store) fileStore0;
      datastoreManager0.processExpires();
  }
}
