/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:52:41 GMT 2026
 */

package com.idc.webchannel.pac4j.extensions.saml.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.idc.webchannel.pac4j.extensions.saml.client.DatabaseLoadedSAML2Clients;
import com.idc.webchannel.pac4j.extensions.saml.dao.api.SamlClientDao;
import java.util.List;
import org.pac4j.core.client.Client;

public class DatabaseLoadedSAML2ClientsTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DatabaseLoadedSAML2Clients databaseLoadedSAML2Clients0 = new DatabaseLoadedSAML2Clients((SamlClientDao) null);
      // Undeclared exception!
      try { 
        databaseLoadedSAML2Clients0.setClients((Client[]) null);
      } catch(UnsupportedOperationException e) {
         //
         // Method setClients(Client... clients) is not implemented.
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DatabaseLoadedSAML2Clients databaseLoadedSAML2Clients0 = new DatabaseLoadedSAML2Clients((SamlClientDao) null);
      // Undeclared exception!
      try { 
        databaseLoadedSAML2Clients0.getClients();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DatabaseLoadedSAML2Clients databaseLoadedSAML2Clients0 = new DatabaseLoadedSAML2Clients((SamlClientDao) null);
      // Undeclared exception!
      try { 
        databaseLoadedSAML2Clients0.setClients((List<Client>) null);
      } catch(UnsupportedOperationException e) {
         //
         // Method setClients(List<Client> clients) is not implemented.
         //
      }
  }
}
