/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 03:19:16 GMT 2026
 */

package com.mbed.coap.packet;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mbed.coap.packet.CoapPacket;
import com.mbed.coap.packet.Code;
import com.mbed.coap.packet.HeaderOptions;
import com.mbed.coap.packet.MessageType;
import com.mbed.coap.packet.Method;
import java.io.PipedInputStream;
import java.net.InetSocketAddress;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;

public class CoapPacketTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Code code0 = Code.C406_NOT_ACCEPTABLE;
      MessageType messageType0 = MessageType.Acknowledgement;
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(8);
      CoapPacket coapPacket0 = new CoapPacket(code0, messageType0, mockInetSocketAddress0);
      int int0 = coapPacket0.hashCode();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Method method0 = Method.POST;
      MessageType messageType0 = MessageType.Acknowledgement;
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("", 1754);
      CoapPacket coapPacket0 = new CoapPacket(method0, messageType0, "", mockInetSocketAddress0);
      try { 
        CoapPacket.read((InetSocketAddress) mockInetSocketAddress0, coapPacket0.DEFAULT_TOKEN);
      } catch(Exception e) {
         //
         // CoAP version 3 not supported
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 51);
      byte[] byteArray0 = new byte[8];
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      coapPacket0.setPayload(byteArray0);
      byte[] byteArray1 = coapPacket0.toByteArray();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 18);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      int int0 = coapPacket0.getMessageId();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("com.mbed.coap.exception.CoapException", 2848);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      CoapPacket coapPacket1 = coapPacket0.createResponse();
      CoapPacket coapPacket2 = coapPacket1.createResponse();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 18);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      HeaderOptions headerOptions0 = coapPacket0.headers();
      coapPacket0.setHeaderOptions(headerOptions0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("{]$C:N/", 562);
      CoapPacket coapPacket0 = new CoapPacket(mockInetSocketAddress0);
      byte byte0 = coapPacket0.getVersion();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 2848);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      String string0 = coapPacket0.toString(true);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 51);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      byte[] byteArray0 = coapPacket0.toByteArray();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Method method0 = Method.POST;
      MessageType messageType0 = MessageType.Acknowledgement;
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("", 1754);
      CoapPacket coapPacket0 = new CoapPacket(method0, messageType0, "", mockInetSocketAddress0);
      byte[] byteArray0 = coapPacket0.getPayload();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Method method0 = Method.POST;
      MessageType messageType0 = MessageType.Acknowledgement;
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("", 1754);
      CoapPacket coapPacket0 = new CoapPacket(method0, messageType0, "", mockInetSocketAddress0);
      byte[] byteArray0 = CoapPacket.serialize(coapPacket0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("{]$C:N/", 562);
      CoapPacket coapPacket0 = new CoapPacket(mockInetSocketAddress0);
      coapPacket0.setPayload("");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("com.mbed.coap.exception.CoapException", 32);
      PipedInputStream pipedInputStream0 = new PipedInputStream((byte)112);
      try { 
        CoapPacket.deserialize(inetSocketAddress0, pipedInputStream0);
      } catch(Exception e) {
         //
         // java.io.IOException: Pipe not connected
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 51);
      byte[] byteArray0 = new byte[8];
      byteArray0[0] = (byte)71;
      CoapPacket coapPacket0 = CoapPacket.read(inetSocketAddress0, byteArray0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("com.mbed.coap.exception.CoapException", 32);
      byte[] byteArray0 = new byte[8];
      byteArray0[0] = (byte)77;
      try { 
        CoapPacket.read(inetSocketAddress0, byteArray0, 32);
      } catch(Exception e) {
         //
         // Wrong TOKEN value, size should be within range 0-8
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 51);
      byte[] byteArray0 = new byte[8];
      byteArray0[0] = (byte)71;
      byteArray0[1] = (byte) (-1);
      CoapPacket coapPacket0 = CoapPacket.read(inetSocketAddress0, byteArray0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 2848);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      CoapPacket coapPacket1 = coapPacket0.createResponse((Code) null);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("{]$C:N/", 562);
      Method method0 = Method.PUT;
      MessageType messageType0 = MessageType.Acknowledgement;
      CoapPacket coapPacket0 = new CoapPacket(method0, messageType0, (String) null, mockInetSocketAddress0);
      // Undeclared exception!
      try { 
        coapPacket0.setMessageId((byte) (-1));
      } catch(IllegalArgumentException e) {
         //
         // invalid messageid, should be within range 0-65535: -1
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Method method0 = Method.POST;
      MessageType messageType0 = MessageType.Acknowledgement;
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("", 1754);
      CoapPacket coapPacket0 = new CoapPacket(method0, messageType0, "", mockInetSocketAddress0);
      String string0 = coapPacket0.getPayloadString();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 18);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      byte[] byteArray0 = new byte[9];
      // Undeclared exception!
      try { 
        coapPacket0.setToken(byteArray0);
      } catch(IllegalArgumentException e) {
         //
         // Wrong TOKEN value, size should be within range 0-8
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Method method0 = Method.POST;
      MessageType messageType0 = MessageType.Acknowledgement;
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("", 1754);
      CoapPacket coapPacket0 = new CoapPacket(method0, messageType0, "", mockInetSocketAddress0);
      byte[] byteArray0 = new byte[2];
      coapPacket0.setToken(byteArray0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("com.mbed.coap.exception.CoapException", 2848);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      CoapPacket coapPacket1 = coapPacket0.createResponse();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("com.mbed.coap.exception.CoapException");
      Code code0 = CoapPacket.writeCode(mockFileOutputStream0, coapPacket1);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Code code0 = Code.C406_NOT_ACCEPTABLE;
      MessageType messageType0 = MessageType.Acknowledgement;
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(8);
      CoapPacket coapPacket0 = new CoapPacket(code0, messageType0, mockInetSocketAddress0);
      boolean boolean0 = coapPacket0.getMustAcknowledge();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 51);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      boolean boolean0 = coapPacket0.getMustAcknowledge();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Code code0 = Code.C406_NOT_ACCEPTABLE;
      MessageType messageType0 = MessageType.Acknowledgement;
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress(8);
      CoapPacket coapPacket0 = new CoapPacket(code0, messageType0, mockInetSocketAddress0);
      String string0 = coapPacket0.toString(false, false, false);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 51);
      byte[] byteArray0 = new byte[8];
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      coapPacket0.setPayload(byteArray0);
      String string0 = coapPacket0.toString(true, false, true);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("{]$C:N/", 562);
      byte[] byteArray0 = new byte[2];
      CoapPacket coapPacket0 = new CoapPacket(mockInetSocketAddress0);
      coapPacket0.setPayload(byteArray0);
      String string0 = coapPacket0.toString(false, false, false);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("com.mbed.coap.exception.CoapException", 32);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      boolean boolean0 = coapPacket0.equals(inetSocketAddress0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("", 51);
      CoapPacket coapPacket0 = new CoapPacket(inetSocketAddress0);
      boolean boolean0 = coapPacket0.equals((Object) null);
  }
}
