/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 03:17:57 GMT 2026
 */

package com.mbed.coap.server.internal;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.mbed.coap.packet.CoapPacket;
import com.mbed.coap.packet.Code;
import com.mbed.coap.packet.MessageType;
import com.mbed.coap.server.internal.CoapServerUtils;
import com.mbed.coap.server.internal.CoapTransaction;
import com.mbed.coap.server.internal.CoapTransactionId;
import com.mbed.coap.server.internal.CoapUdpMessaging;
import com.mbed.coap.server.internal.TransactionManager;
import com.mbed.coap.transport.CoapTransport;
import com.mbed.coap.transport.InMemoryCoapTransport;
import com.mbed.coap.transport.TransportContext;
import com.mbed.coap.utils.Callback;
import java.net.InetSocketAddress;
import java.util.Collection;
import java.util.Optional;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.function.Consumer;
import org.evosuite.runtime.ViolatedAssumptionAnswer;

public class TransactionManagerTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      CoapServerUtils.InternalRequestCallback coapServerUtils_InternalRequestCallback0 = new CoapServerUtils.InternalRequestCallback((Callback<CoapPacket>) null);
      Code code0 = Code.C202_DELETED;
      MessageType messageType0 = MessageType.Confirmable;
      InetSocketAddress inetSocketAddress0 = InMemoryCoapTransport.createAddress(0);
      CoapPacket coapPacket0 = new CoapPacket(code0, messageType0, inetSocketAddress0);
      ScheduledThreadPoolExecutor scheduledThreadPoolExecutor0 = new ScheduledThreadPoolExecutor(0);
      InMemoryCoapTransport inMemoryCoapTransport0 = new InMemoryCoapTransport(0, scheduledThreadPoolExecutor0);
      CoapUdpMessaging coapUdpMessaging0 = new CoapUdpMessaging(inMemoryCoapTransport0);
      TransportContext transportContext0 = mock(TransportContext.class, new ViolatedAssumptionAnswer());
      Consumer<CoapTransactionId> consumer0 = (Consumer<CoapTransactionId>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      CoapTransaction coapTransaction0 = new CoapTransaction(coapServerUtils_InternalRequestCallback0, coapPacket0, coapUdpMessaging0, transportContext0, consumer0);
      boolean boolean0 = transactionManager0.addTransactionAndGetReadyToSend(coapTransaction0);
      // Undeclared exception!
      try { 
        transactionManager0.close();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      Collection<CoapTransaction> collection0 = transactionManager0.findTimeoutTransactions(1152L);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      // Undeclared exception!
      try { 
        transactionManager0.unlockOrRemoveAndGetNext((CoapTransactionId) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      int int0 = transactionManager0.getNumberOfTransactions();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      // Undeclared exception!
      try { 
        transactionManager0.removeAndLock((CoapTransactionId) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      // Undeclared exception!
      try { 
        transactionManager0.setMaximumEndpointQueueSize(0);
      } catch(IllegalArgumentException e) {
         //
         // Endpoint queue size should be in range 1..65536
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      transactionManager0.setMaximumEndpointQueueSize(65536);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      // Undeclared exception!
      try { 
        transactionManager0.setMaximumEndpointQueueSize(65539);
      } catch(IllegalArgumentException e) {
         //
         // Endpoint queue size should be in range 1..65536
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      CoapServerUtils.InternalRequestCallback coapServerUtils_InternalRequestCallback0 = new CoapServerUtils.InternalRequestCallback((Callback<CoapPacket>) null);
      Code code0 = Code.C202_DELETED;
      MessageType messageType0 = MessageType.Confirmable;
      InetSocketAddress inetSocketAddress0 = InMemoryCoapTransport.createAddress(0);
      CoapPacket coapPacket0 = new CoapPacket(code0, messageType0, inetSocketAddress0);
      CoapTransport coapTransport0 = InMemoryCoapTransport.create(0);
      CoapUdpMessaging coapUdpMessaging0 = new CoapUdpMessaging(coapTransport0);
      TransportContext transportContext0 = mock(TransportContext.class, new ViolatedAssumptionAnswer());
      Consumer<CoapTransactionId> consumer0 = (Consumer<CoapTransactionId>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      CoapTransaction coapTransaction0 = new CoapTransaction(coapServerUtils_InternalRequestCallback0, coapPacket0, coapUdpMessaging0, transportContext0, consumer0);
      boolean boolean0 = transactionManager0.addTransactionAndGetReadyToSend(coapTransaction0, true);
      boolean boolean1 = transactionManager0.addTransactionAndGetReadyToSend(coapTransaction0, true);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      Code code0 = Code.C202_DELETED;
      MessageType messageType0 = MessageType.Confirmable;
      InetSocketAddress inetSocketAddress0 = InMemoryCoapTransport.createAddress(0);
      CoapPacket coapPacket0 = new CoapPacket(code0, messageType0, inetSocketAddress0);
      Optional<CoapTransaction> optional0 = transactionManager0.findMatchAndRemoveForSeparateResponse(coapPacket0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      Code code0 = Code.C202_DELETED;
      InetSocketAddress inetSocketAddress0 = InMemoryCoapTransport.createAddress(0);
      MessageType messageType0 = MessageType.NonConfirmable;
      CoapPacket coapPacket0 = new CoapPacket(code0, messageType0, inetSocketAddress0);
      Optional<CoapTransaction> optional0 = transactionManager0.findMatchAndRemoveForSeparateResponse(coapPacket0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      CoapPacket coapPacket0 = new CoapPacket((InetSocketAddress) null);
      CoapPacket coapPacket1 = coapPacket0.createResponse();
      Optional<CoapTransaction> optional0 = transactionManager0.findMatchAndRemoveForSeparateResponse(coapPacket1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      Code code0 = Code.C202_DELETED;
      InetSocketAddress inetSocketAddress0 = InMemoryCoapTransport.createAddress(0);
      MessageType messageType0 = MessageType.NonConfirmable;
      CoapPacket coapPacket0 = new CoapPacket(code0, messageType0, inetSocketAddress0);
      CoapPacket coapPacket1 = coapPacket0.createResponse();
      Optional<CoapTransaction> optional0 = transactionManager0.findMatchAndRemoveForSeparateResponse(coapPacket1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TransactionManager transactionManager0 = new TransactionManager();
      transactionManager0.close();
  }
}
