/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:06:59 GMT 2026
 */

package io.datakernel.jmx;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import io.datakernel.di.Key;
import io.datakernel.di.module.UniqueQualifierImpl;
import io.datakernel.jmx.DynamicMBeanFactory;
import io.datakernel.jmx.JmxBeanSettings;
import io.datakernel.jmx.JmxRegistry;
import io.datakernel.worker.WorkerPool;
import java.lang.annotation.Annotation;
import java.time.Duration;
import java.util.LinkedList;
import javax.management.MBeanServer;
import javax.management.ObjectInstance;
import javax.management.ObjectName;
import org.evosuite.runtime.ViolatedAssumptionAnswer;

public class JmxRegistryTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      String[] stringArray0 = jmxRegistry0.getRefreshStats();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      JmxRegistry jmxRegistry1 = jmxRegistry0.withScopes(false);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      String string0 = jmxRegistry0.getRefreshPeriod();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, (DynamicMBeanFactory) null);
      int int0 = jmxRegistry0.getRegisteredPools();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      Duration duration0 = Duration.ofSeconds((-1L));
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create(duration0, (-1));
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      int int0 = jmxRegistry0.getTotallyRegisteredMBeans();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      int int0 = jmxRegistry0.getMaxRefreshesPerOneCycle();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, (DynamicMBeanFactory) null);
      // Undeclared exception!
      try { 
        jmxRegistry0.setMaxRefreshesPerOneCycle(672);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      Duration duration0 = Duration.ofHours(4183L);
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create(duration0, 0);
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      int int0 = jmxRegistry0.getRegisteredSingletons();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      // Undeclared exception!
      try { 
        jmxRegistry0.setRefreshPeriod("(Named(java.lang.String@0000000008)");
      } catch(IllegalArgumentException e) {
         //
         // Invalid duration: (Named(java.lang.String@0000000008)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ObjectInstance objectInstance0 = mock(ObjectInstance.class, new ViolatedAssumptionAnswer());
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      doReturn(objectInstance0).when(mBeanServer0).registerMBean(any() , any(javax.management.ObjectName.class));
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      Class<Annotation> class0 = Annotation.class;
      Key<Annotation> key0 = Key.ofName(class0, "(Named(java.lang.String@0000000012)");
      JmxBeanSettings jmxBeanSettings0 = JmxBeanSettings.defaultSettings();
      jmxRegistry0.registerSingleton(key0, jmxRegistry0, jmxBeanSettings0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      jmxRegistry0.addWorkerPoolKey((WorkerPool) null, (Key<?>) null);
      // Undeclared exception!
      try { 
        jmxRegistry0.addWorkerPoolKey((WorkerPool) null, (Key<?>) null);
      } catch(IllegalArgumentException e) {
         //
         // Key already added
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      JmxBeanSettings jmxBeanSettings0 = JmxBeanSettings.create();
      // Undeclared exception!
      try { 
        jmxRegistry0.registerSingleton((Key<?>) null, jmxBeanSettings0, jmxBeanSettings0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Class<Annotation> class0 = Annotation.class;
      Key<Annotation> key0 = Key.of(class0);
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      jmxRegistry0.unregisterSingleton(key0, linkedList0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      // Undeclared exception!
      try { 
        jmxRegistry0.unregisterSingleton((Key<?>) null, jmxRegistry0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      boolean boolean0 = linkedList0.add((Object) dynamicMBeanFactory0);
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      JmxBeanSettings jmxBeanSettings0 = JmxBeanSettings.defaultSettings();
      // Undeclared exception!
      try { 
        jmxRegistry0.registerWorkers((WorkerPool) null, (Key<?>) null, linkedList0, jmxBeanSettings0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      LinkedList<ObjectName> linkedList0 = new LinkedList<ObjectName>();
      JmxBeanSettings jmxBeanSettings0 = JmxBeanSettings.defaultSettings();
      // Undeclared exception!
      try { 
        jmxRegistry0.registerWorkers((WorkerPool) null, (Key<?>) null, linkedList0, jmxBeanSettings0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      boolean boolean0 = linkedList0.offerFirst(dynamicMBeanFactory0);
      Class<Annotation> class0 = Annotation.class;
      Object object0 = new Object();
      boolean boolean1 = linkedList0.offerLast(object0);
      Key<Annotation> key0 = Key.of(class0);
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      JmxBeanSettings jmxBeanSettings0 = JmxBeanSettings.create();
      jmxRegistry0.registerWorkers((WorkerPool) null, key0, linkedList0, jmxBeanSettings0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      boolean boolean0 = linkedList0.offerFirst(dynamicMBeanFactory0);
      Class<Annotation> class0 = Annotation.class;
      Key<Annotation> key0 = Key.of(class0);
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      jmxRegistry0.unregisterWorkers((WorkerPool) null, key0, linkedList0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      jmxRegistry0.unregisterWorkers((WorkerPool) null, (Key<?>) null, linkedList0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      boolean boolean0 = linkedList0.offerFirst(dynamicMBeanFactory0);
      Class<Annotation> class0 = Annotation.class;
      Key<Annotation> key0 = Key.of(class0);
      boolean boolean1 = linkedList0.add((Object) class0);
      JmxRegistry jmxRegistry0 = JmxRegistry.create((MBeanServer) null, dynamicMBeanFactory0);
      jmxRegistry0.unregisterWorkers((WorkerPool) null, key0, linkedList0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      doReturn((ObjectInstance) null).when(mBeanServer0).registerMBean(any() , any(javax.management.ObjectName.class));
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      Class<Object> class0 = Object.class;
      Key<Object> key0 = Key.of(class0, (Object) class0);
      jmxRegistry0.registerSingleton(key0, jmxRegistry0, (JmxBeanSettings) null);
      jmxRegistry0.unregisterAll();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DynamicMBeanFactory dynamicMBeanFactory0 = DynamicMBeanFactory.create();
      Class<Object> class0 = Object.class;
      UniqueQualifierImpl uniqueQualifierImpl0 = new UniqueQualifierImpl();
      Key<Object> key0 = Key.of(class0, (Object) uniqueQualifierImpl0);
      MBeanServer mBeanServer0 = mock(MBeanServer.class, new ViolatedAssumptionAnswer());
      doReturn((ObjectInstance) null).when(mBeanServer0).registerMBean(any() , any(javax.management.ObjectName.class));
      JmxRegistry jmxRegistry0 = JmxRegistry.create(mBeanServer0, dynamicMBeanFactory0);
      jmxRegistry0.registerSingleton(key0, jmxRegistry0, (JmxBeanSettings) null);
  }
}
