/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:07:52 GMT 2026
 */

package io.datakernel.remotefs;

import org.junit.Test;
import static org.junit.Assert.*;

public class TestCachedFsClient {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = "io.datakernel.remotefs.CachedFsClient";
      Thread thread0 = Thread.currentThread();
      ClassLoader classLoader0 = thread0.getContextClassLoader();
      boolean boolean0 = true;
      // Undeclared exception!
      try { 
        Class.forName(string0, boolean0, classLoader0);
      } catch(NoClassDefFoundError e) {
      }
  }
}
