/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 17 02:30:07 GMT 2026
 */

package com.igormaznitsa.mvngolang.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.igormaznitsa.mvngolang.utils.PackageList;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;

public class PackageListTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1");
      String string0 = packageList_Package0.getTag();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1");
      String string0 = packageList_Package0.getBranch();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("", (String) null, "", (String) null);
      String string0 = packageList_Package0.getRevision();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("", "", "filter", "");
      String string0 = packageList_Package0.toString();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("Q", "Q", "Q", "Q");
      String string0 = packageList_Package0.makeString();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1", "com.igormaznitsa.mvngolang.utils.PackageList$1");
      String string0 = packageList_Package0.getPackage();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MockFile mockFile0 = new MockFile("#include0~v{kjm&yHkAY`-`Q");
      PackageList.ContentProvider packageList_ContentProvider0 = mock(PackageList.ContentProvider.class, new ViolatedAssumptionAnswer());
      doReturn("package: #include0~v{kjm&yHkAY`-`Q,branch: #include0~v{kjm&yHkAY`-`Q,tag: #include0~v{kjm&yHkAY`-`Q,revision: #include0~v{kjm&yHkAY`-`Q").when(packageList_ContentProvider0).readContent(any(java.io.File.class));
      PackageList packageList0 = new PackageList(mockFile0, "#include0~v{kjm&yHkAY`-`Q", packageList_ContentProvider0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockFile mockFile0 = new MockFile("");
      PackageList.ContentProvider packageList_ContentProvider0 = mock(PackageList.ContentProvider.class, new ViolatedAssumptionAnswer());
      PackageList packageList0 = new PackageList(mockFile0, "", packageList_ContentProvider0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockFile mockFile0 = new MockFile("FBKSrH !olkA~xeL");
      PackageList.ContentProvider packageList_ContentProvider0 = mock(PackageList.ContentProvider.class, new ViolatedAssumptionAnswer());
      PackageList packageList0 = new PackageList(mockFile0, "//Objec must be NULL", packageList_ContentProvider0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = PackageList.removeComment("//Q", true);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockFile mockFile0 = new MockFile("org.apache.commons.io.file.Counters$LongCounter");
      PackageList.ContentProvider packageList_ContentProvider0 = mock(PackageList.ContentProvider.class, new ViolatedAssumptionAnswer());
      PackageList packageList0 = null;
      try {
        packageList0 = new PackageList(mockFile0, "package: getFileNameString,branch: null,tag: \"package: package: Q,branch: Q,tag: Q,revision: Q,branch: package: package: Q,branch: Q,tag: Q,revision: Q,branch: Q,tag: package: Q,branch: Q,tag: Q,revision: Q,revision: com.igormaznitsa.mvngolang.utils.PackageList$1,tag: com.igormaznitsa.mvngolang.utils.PackageList$1,revision: package: Q,branch: Q,tag: Q,revision: Q,revision: Q", packageList_ContentProvider0);
      } catch(Throwable e) {
         //
         // package: getFileNameString,branch: null,tag: \"package: package: Q,branch: Q,tag: Q,revision: Q,branch: package: package: Q,branch: Q,tag: Q,revision: Q,branch: Q,tag: package: Q,branch: Q,tag: Q,revision: Q,revision: com.igormaznitsa.mvngolang.utils.PackageList$1,tag: com.igormaznitsa.mvngolang.utils.PackageList$1,revision: package: Q,branch: Q,tag: Q,revision: Q,revision: Q
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = PackageList.removeComment("\"8])~db]\"", true);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = PackageList.removeComment("//Q", false);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = PackageList.removeComment("\"'/#4H_e*<+p", true);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = PackageList.removeQuotes("");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String string0 = PackageList.removeQuotes("\"HqMquaD$K+&Pt/");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = PackageList.removeQuotes("\"Unsupported key: \"");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MockFile mockFile0 = new MockFile("-");
      PackageList.ContentProvider packageList_ContentProvider0 = mock(PackageList.ContentProvider.class, new ViolatedAssumptionAnswer());
      PackageList packageList0 = null;
      try {
        packageList0 = new PackageList(mockFile0, "-", packageList_ContentProvider0);
      } catch(Throwable e) {
         //
         // -
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MockFile mockFile0 = new MockFile("SwL:^82rHyyq t", "SwL:^82rHyyq t");
      PackageList.ContentProvider packageList_ContentProvider0 = mock(PackageList.ContentProvider.class, new ViolatedAssumptionAnswer());
      PackageList packageList0 = null;
      try {
        packageList0 = new PackageList(mockFile0, "SwL:^82rHyyq t", packageList_ContentProvider0);
      } catch(IllegalArgumentException e) {
         //
         // Unsupported key: swl
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("2^'TF<\"k\"s2Ntl", "2^'TF<\"k\"s2Ntl", "", (String) null);
      boolean boolean0 = packageList_Package0.doesNeedCvsProcessing();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("getFileNameString", (String) null, "\"package: package: Q,branch: Q,tag: Q,revision: Q,branch: package: package: Q,branch: Q,tag: Q,revision: Q,branch: Q,tag: package: Q,branch: Q,tag: Q,revision: Q,revision: com.igormaznitsa.mvngolang.utils.PackageList$1,tag: com.igormaznitsa.mvngolang.utils.PackageList$1,revision: package: Q,branch: Q,tag: Q,revision: Q", "Q");
      boolean boolean0 = packageList_Package0.doesNeedCvsProcessing();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("System", (String) null, (String) null, (String) null);
      boolean boolean0 = packageList_Package0.doesNeedCvsProcessing();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PackageList.Package packageList_Package0 = new PackageList.Package("System", (String) null, (String) null, "System");
      boolean boolean0 = packageList_Package0.doesNeedCvsProcessing();
  }
}
