/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 03:21:29 GMT 2026
 */

package com.igormaznitsa.mvngolang;

import org.junit.Test;
import static org.junit.Assert.*;
import com.igormaznitsa.mvngolang.GolangBuildMojo;
import com.igormaznitsa.mvngolang.utils.ProxySettings;
import org.apache.maven.plugin.MojoFailureException;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;

public class GolangBuildMojoTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultFolder("GO111MODULE");
      String[] stringArray0 = new String[2];
      golangBuildMojo0.setPackages(stringArray0);
      golangBuildMojo0.beforeExecution((ProxySettings) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      boolean boolean0 = golangBuildMojo0.isStrip();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      boolean boolean0 = golangBuildMojo0.isSkip();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultFolder("go.sum");
      golangBuildMojo0.setResultName("mvn-golang");
      golangBuildMojo0.afterExecution((ProxySettings) null, false);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      boolean boolean0 = golangBuildMojo0.isCommandSupportVerbose();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      String string0 = golangBuildMojo0.getAttachClassifier();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setStrip(true);
      // Undeclared exception!
      try { 
        golangBuildMojo0.getAdditionalCommandFlags();
      } catch(AssertionError e) {
         //
         // Object must not be NULL
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      String string0 = golangBuildMojo0.getAttachType();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      String string0 = golangBuildMojo0.getGoCommand();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultFolder("go.sum");
      golangBuildMojo0.beforeExecution((ProxySettings) null);
      golangBuildMojo0.beforeExecution((ProxySettings) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultFolder("?w_xtM");
      try { 
        golangBuildMojo0.beforeExecution((ProxySettings) null);
      } catch(MojoFailureException e) {
         //
         // Can't create folder : ?w_xtM
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultFolder("go.sum");
      golangBuildMojo0.setBuildMode((String) null);
      golangBuildMojo0.beforeExecution((ProxySettings) null);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultFolder("go.sum");
      String[] stringArray0 = new String[0];
      golangBuildMojo0.setPackages(stringArray0);
      golangBuildMojo0.beforeExecution((ProxySettings) null);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      ProxySettings proxySettings0 = new ProxySettings();
      golangBuildMojo0.afterExecution(proxySettings0, true);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("GO111MODULE\\mvn-golang");
      boolean boolean0 = FileSystemHandling.createFolder(evoSuiteFile0);
      golangBuildMojo0.setResultFolder("GO111MODULE");
      golangBuildMojo0.setResultName("mvn-golang");
      ProxySettings proxySettings0 = new ProxySettings();
      try { 
        golangBuildMojo0.afterExecution(proxySettings0, false);
      } catch(MojoFailureException e) {
         //
         // Can't find generated target file : D:\\pilot_delivery\\pilot_delivery\\pilot_bundle_24\\compiledrepos\\54620819\\mvn-golang-wrapper\\GO111MODULE\\mvn-golang
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultFolder("GO111MODULE");
      golangBuildMojo0.setResultName("mvn-golang");
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("GO111MODULE\\mvn-golang");
      boolean boolean0 = FileSystemHandling.appendLineToFile(evoSuiteFile0, "go.sum");
      golangBuildMojo0.afterExecution((ProxySettings) null, false);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultName("none");
      String[] stringArray0 = golangBuildMojo0.getAdditionalCommandFlags();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultName("mvn-golang");
      String[] stringArray0 = new String[1];
      golangBuildMojo0.setPackages(stringArray0);
      // Undeclared exception!
      try { 
        golangBuildMojo0.getCommandFlags();
      } catch(AssertionError e) {
         //
         // Object must not be NULL
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GolangBuildMojo golangBuildMojo0 = new GolangBuildMojo();
      golangBuildMojo0.setResultName("mvn-golang");
      String[] stringArray0 = new String[7];
      golangBuildMojo0.setPackages(stringArray0);
      String[] stringArray1 = golangBuildMojo0.getCommandFlags();
  }
}
